### ISSUE TITLE
Marauder axe handle recipe broken in 1.6.1

### ISSUE THREAD

**Issue by ArMoReDfUrY** [AzureDoom/Doom-Crucible#2]
you forgot to put an _ in the key for netherbrick so the recipe is uncraftable.

minecraft:netherbrick
       should be 
minecraft:nether_brick
easy fix.
BTW thank you and your artists for making this and updating it so regularly.

**Comment by AzureDoom** [comment]
This has been fixed for both 1.14.4 and 1.15.2
